apiVersion: v1
kind: Service
metadata:
  name: rest-service
  namespace: rest-service
  labels:
    app: rest-service
spec:
  type: ClusterIP
  selector:
    app: rest-service
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
